# Generated by Django 4.2.14 on 2024-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mein', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='category_rasm/'),
        ),
        migrations.AlterField(
            model_name='category_field',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='category_field_rasm/'),
        ),
    ]
